#!/bin/bash

# Source ~/.xprofile. Required because I switched display managers from gdm to lightdm.
# gdm sources ~/.profile, lightdm does not.
# so doing the proper thing and sourcing ~/.xprofile which sets some xwindows stuff (like turning off
# screensavers/power management, before sourcing ~/.profile)
#
if [ -f "$HOME/.xprofile" ]; then
    . "$HOME/.xprofile"
fi

# Kill input daemons
killall ibus-daemon ibus fcitx fcitx5 uim-xim 2>/dev/null

unset GTK_IM_MODULE
unset QT_IM_MODULE
unset XMODIFIERS

if [ "$XDG_CURRENT_DESKTOP" = "dwm" ]; then
    # was having issues on the framework laptop with message exhaustion,
    # keyboard inputs would only be received after the mouse was moved
    picom --backend xrender --vsync --xrender-sync --xrender-sync-fence &
fi
exec /home/indy/.local/bin/dwm &> /tmp/dwm-123
