#!/usr/bin/env bash

case $HOSTNAME in
  (fedora) AUDIOCARD=1;;
  (zara) AUDIOCARD=1;;
  (zek) AUDIOCARD=1;;
  (*) AUDIOCARD=0;;
esac

if [ "$1" = "dec" ]
then
  amixer -q -c $AUDIOCARD sset Master 5%-
elif [ "$1" = "inc" ]
then
  amixer -q -c $AUDIOCARD sset Master 5%+
elif [ "$1" = "toggle" ]
then
  amixer -q -c $AUDIOCARD -D pulse sset Master toggle
fi

dwm-bar-update
