#!/bin/sh

if [ "$1" = "dec" ]
then
  amixer -q sset Master 5%-
elif [ "$1" = "inc" ]
then
  amixer -q sset Master 5%+
elif [ "$1" = "toggle" ]
then
  amixer -q -D pulse sset Master toggle
elif [ "$1" = "playpause" ]
then
  rhythmbox-client --play-pause
elif [ "$1" = "prev" ]
then
  rhythmbox-client --previous
elif [ "$1" = "next" ]
then
  rhythmbox-client --next
fi

dwm-bar-update
