#!/usr/bin/env bash

case $HOSTNAME in
zara) AUDIOCARD=1 ;;
zek) AUDIOCARD=1 ;;
*) AUDIOCARD=0 ;;
esac

# ----------------------------------------

if [ "$(amixer -c $AUDIOCARD sget Master | awk -F' ' '/Mono:/ { print $6 }')" = "[on]" ]; then
    # audible
    AUDIO=$(printf " %s" "$(amixer -c $AUDIOCARD sget Master | awk -F"[][]" '/Mono:/ { print $2 }')")
else
    # muted
    AUDIO=$(printf "")
fi

# ----------------------------------------

if [ -d "/sys/class/power_supply/BAT0" ]; then
    read -r status </sys/class/power_supply/BAT0/status
    read -r capacity </sys/class/power_supply/BAT0/capacity

    if [ "$capacity" -lt 20 ]; then
        BATTERY=$(printf " %s%% %s" "$capacity" "$status")
    elif [ "$capacity" -lt 33 ]; then
        BATTERY=$(printf " %s%% %s" "$capacity" "$status")
    elif [ "$capacity" -lt 66 ]; then
        BATTERY=$(printf " %s%% %s" "$capacity" "$status")
    else
        BATTERY=$(printf " %s%% %s" "$capacity" "$status")
    fi
fi

# ----------------------------------------

diskspace() {
    df -h | grep ^${1-} | awk '{print $4 " Free"}'
}

case $HOSTNAME in
anarch) DISKSPACE=$(diskspace /dev/sdc2) ;;
theseus) DISKSPACE=$(diskspace /dev/sdc2) ;;
dellboy) DISKSPACE=$(diskspace /dev/nvme0n1p3) ;;
zara) DISKSPACE=$(diskspace /dev/nvme0n1p2) ;;
zek) DISKSPACE=$(diskspace /dev/sda2) ;;
*) DISKSPACE=$(printf "(dwm-bar) unknown hostname") ;;
esac

# ----------------------------------------

DATETIME=$(printf "%s" "$(date '+%a %b %d %R')")

# ----------------------------------------

if [ -z "$BATTERY" ]; then
    xsetroot -name " $AUDIO    $DISKSPACE    $DATETIME "
else
    xsetroot -name " $AUDIO   $BATTERY    $DISKSPACE    $DATETIME "
fi
