#!/usr/bin/env bash

# for some reason zek has the audio card at 1, everything else has it at 0
case $HOSTNAME in
  (zek) AUDIOCARD=1;;
  (*) AUDIOCARD=0;;
esac

# ----------------------------------------

if [ "$(amixer -c $AUDIOCARD sget Master | awk -F' ' '/Mono:/ { print $6 }')" = "[on]" ]
then
    # audible
    AUDIO=$(printf "Audio: %s" "$(amixer -c $AUDIOCARD sget Master | awk -F"[][]" '/Mono:/ { print $2 }')")
else
    # muted
    AUDIO=$(printf "Muted")
fi

# ----------------------------------------

if [ -d "/sys/class/power_supply/BAT0" ]
then
    read -r status </sys/class/power_supply/BAT0/status
    read -r capacity </sys/class/power_supply/BAT0/capacity
    BATTERY=$(printf "Battery %s: %s%%" "$status" "$capacity")
fi

# ----------------------------------------

diskspace() {
    df -h | grep ^${1-} | awk '{print $4 " free"}'
}

case $HOSTNAME in
  (anarch) DISKSPACE=$(diskspace /dev/sdc2);;
  (theseus) DISKSPACE=$(diskspace /dev/sdc2);;
  (dellboy) DISKSPACE=$(diskspace /dev/nvme0n1p3);;
  (zek) DISKSPACE=$(diskspace /dev/sda2);;
  (*) DISKSPACE=$(printf "(dwm-bar) unknown hostname");;
esac

# ----------------------------------------

DATETIME=$(printf "%s" "$(date '+%a %b %d %R')")

# ----------------------------------------

if [ -z "$BATTERY" ]
then
    xsetroot -name " $AUDIO   $DISKSPACE   $DATETIME "
else
    xsetroot -name " $AUDIO   $BATTERY   $DISKSPACE   $DATETIME "
fi
